Revert 220166 "Archive webkit_tests results on android bots if r..."
Android bot throws an exception since this change.

< cat /b/build/slave/WebKit_Android__Nexus4_/build/src/out/Release/test_logs/unit_test.log
An instance of host heart beart running... will kill
Traceback (most recent call last):
  File "build/android/buildbot/bb_device_steps.py", line 469, in <module>
    sys.exit(main(sys.argv))
  File "build/android/buildbot/bb_device_steps.py", line 465, in main
    MainTestWrapper(options)
  File "build/android/buildbot/bb_device_steps.py", line 402, in MainTestWrapper
    bb_utils.RunSteps(options.test_filter, GetTestStepCmds(), options)
  File "/b/build/slave/WebKit_Android__Nexus4_/build/src/build/android/buildbot/bb_utils.py", line 97, in RunSteps
    cmd(options)
  File "build/android/buildbot/bb_device_steps.py", line 257, in RunWebkitLayoutTests
    '--builder-name', options.build_properties.get('buildername', '')])
  File "/b/build/slave/WebKit_Android__Nexus4_/build/src/build/android/buildbot/bb_utils.py", line 56, in RunCmd
    code = SpawnCmd(command, stdout, cwd).wait()
  File "/b/build/slave/WebKit_Android__Nexus4_/build/src/build/android/buildbot/bb_utils.py", line 49, in SpawnCmd
    return subprocess.Popen(command, cwd=cwd, stdout=stdout)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

> Archive webkit_tests results on android bots if requested.
> 
> R=ilevy@chromium.org, bulach@chromium.org, peter@chromium.org
> BUG=276076
> 
> Review URL: https://chromiumcodereview.appspot.com/22825016

TBR=dpranke@chromium.org

Review URL: https://codereview.chromium.org/23601007

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a342011ddee4d8cc568c9e97da2a443415c93a66