Reverting 7573.
Doing a full build seems always fine. The issue is for incremental builds, it corrupts the PDBs. Errors look like:

glue.lib(autofill_form.obj) : fatal error LNK1318: Unexpected PDB error; RPC (23) '(0x000006BA)'
...\xmemory(155) : error C2471: cannot update program database '...\debug\obj\plugin_tests\vc80.pdb'

We'll probably need to upgrade to VS2008 to add it back.
Review URL: http://codereview.chromium.org/17208

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e7a023be01011f2a2734e2c72d1d2c632a86e272