Revert 136728 - Disable precompiled headers when using 2010 on an Official build.
(Reverted due to build errors on Win Builder 2010 (dbg):
 NameError: name 'buildtype' is not defined while evaluating condition 'OS=="win"
 and MSVS_VERSION=="2010" and buildtype!="Official"' in src\build\all.gyp while
 trying to load src\build\all.gyp)

bug=127875
R=bradnelson

Review URL: https://chromiumcodereview.appspot.com/10392063

TBR=kerz@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10387096

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 75de721b7a3aa1b97189dac543487cf06080ec42