Revert of Run android tests through runtest.py. (https://codereview.chromium.org/414383002/)
Reason for revert:
Looks like the cause of http://build.chromium.org/p/chromium.linux/builders/Android%20Tests%20%28dbg%29/builds/22085 failing.

runtest.py was repeatedly unable to find the test targets it was supposed to run.

partial log:
@@@BUILD_STEP base_unittests@@@
> /b/build/scripts/slave/runtest.py '--factory-properties={"generate_gtest_json": true, "target": "Debug", "gclient_env": {}, "build_url": "http://build1-a1/b/build/slave/Android_Builder__dbg_/chrome_staging/full-build-linux.zip", "clobber": false, "GYP_DEFINES": " component=shared_library", "target_os": "android", "android_bot_id": "main-tests-dbg"}' '--build-properties={"parentname": "Android Builder (dbg)", "got_nacl_revision": "13580", "parent_wk_revision": "179716", "parent_got_v8_revision": "22960", "parent_got_swarming_client_revision": "bbf1fcca7932d92cca9d7dab46ea271a7f6d61fb", "got_revision": "288139", "parent_revision": "288139", "blamelist_real": ["achaulk@chromium.org", "jamescook@chromium.org", "mef@chromium.org", "morrita@chromium.org", "varkha@chromium.org", "zty@chromium.org (:zty)"], "got_webkit_revision_git": "08c40136a44dd5b3f5bf976d5c75e7623afb8e29", "parent_slavename": "build1-a1", "got_v8_revision_git": "9d72b8dd94263d9f500f18255d67f0c7b8c3527a", "got_webrtc_revision_git": "a288b8cbb568cbf1735e6d5d0012524f4f8e5f74", "buildnumber": 22085, "got_webkit_revision": "179716", "parent_scheduler": "android", "got_swarming_client_revision": "bbf1fcca7932d92cca9d7dab46ea271a7f6d61fb", "parent_buildnumber": "63404", "slavename": "build42-a1", "blamelist": "achaulk@chromium.org,jamescook@chromium.org,mef@chromium.org,morrita@chromium.org,varkha@chromium.org,zty@chromium.org", "branch": "src", "patchset": "", "issue": "", "revision": "288139", "workdir": "/b/build/slave/Android_Tests__dbg_", "repository": "svn://svn-mirror.golo.chromium.org/chrome/trunk", "buildername": "Android Tests (dbg)", "parent_try_job_key": "", "got_webrtc_revision": "6825", "mastername": "chromium.linux", "parent_got_webkit_revision": "179716", "parent_builddir": "", "parent_branch": "src", "got_nacl_revision_git": "1fb9738130a80c961cf1ed46cdb38caf0d165543", "scheduler": "android_trigger_dbg", "requester": "", "buildbotURL": "http://build.chromium.org/p/chromium.linux/", "parent_cr_revision": "288139", "got_revision_git": "3afe85add41986693e47da5e33a01a2989c96354", "rietveld": "", "parent_got_nacl_revision": "13580", "parent_buildername": "Android Builder (dbg)", "got_v8_revision": "22960", "parent_got_revision": "288139", "project": "", "patch_url": "", "parentslavename": "build1-a1", "root": "", "primary_repo": ""}' --test-platform android --generate-json-file -o gtest-results/base_unittests --annotate gtest --build-number 22085 --builder-name 'Android Tests (dbg)' base_unittests --verbose
[Running on builder: "Android Tests (dbg)"]
DBUS_SESSION_BUS_ADDRESS env var not found, starting dbus-launch
 setting DBUS_SESSION_BUS_ADDRESS to unix:abstract=/tmp/dbus-p2NSrlwT6t,guid=118a14e22115547464aef590000002f4
 setting DBUS_SESSION_BUS_PID to 8386
Additional test environment:
  LLVM_SYMBOLIZER_PATH=/b/build/slave/Android_Tests__dbg_/build/src/third_party/llvm-build/Release+Asserts/bin/llvm-symbolizer

src/build/android/test_runner.py gtest --release -s base_unittests
Traceback (most recent call last):
  File "src/build/android/test_runner.py", line 836, in <module>
    sys.exit(main())
  File "src/build/android/test_runner.py", line 832, in main
    return command_option_parser.ParseAndExecute(option_parser)
  File "/b/build/slave/Android_Tests__dbg_/build/src/build/android/pylib/utils/command_option_parser.py", line 75, in ParseAndExecute
    return cmd.run_command_func(argv[1], options, args, option_parser)
  File "src/build/android/test_runner.py", line 746, in RunTestsCommand
    return _RunGTests(options, devices)
  File "src/build/android/test_runner.py", line 527, in _RunGTests
    runner_factory, tests = gtest_setup.Setup(gtest_options, devices)
  File "/b/build/slave/Android_Tests__dbg_/build/src/build/android/pylib/gtest/setup.py", line 325, in Setup
    % test_options.suite_name)
Exception: Did not find base_unittests target. Ensure it has been built.
using JSON summary output instead of gtest XML
No data was available to update the JSON results

Original issue's description:
> Run android tests through runtest.py.
> 
> This CL re-lands https://codereview.chromium.org/410033002 while addressed a few issues.
> 1. --results-directory must be passed along with --generate-gtest-json
> 2. --test-platform, --annotate, --build-number, --builder-name should be passed in order to upload results to correct dashboard
> 3. This CL depends on https://codereview.chromium.org/414223011/ to fix a bug in runtest.py
> 
> BUG=329102
> R=yfriedman@chromium.org, navabi@chromium.org, jbudorick@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=288134

TBR=jbudorick@chromium.org,navabi@chromium.org,yfriedman@chromium.org,zty@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=329102

Review URL: https://codereview.chromium.org/455493002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 689c2631f1e7a5cfce0f36413336daa53bac9d6a