Android: fix link error for android_full_debug=1
android_full_debug=1 fails to link with "undefined reference to
__cxa_bad_typeid". Work around this by telling the linker to ignore
unused input sections.

Review URL: https://chromiumcodereview.appspot.com/13772007

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 3f05e9167ba720356bdcf866d7456e3c3e53056d