Revert 262031 "When "linux_use_gold_binary" is set, we now use g..."
Suspected of causing:

http://build.chromium.org/p/chromium.linux/builders/Linux%20Builder%20(dbg)/builds/71338/steps/compile/logs/stdio

[13474/21627] CXX obj/cc/animation/cc_unittests.scrollbar_animation_controller_linear_fade_unittest.o
FAILED: cd ../../remoting; python ../tools/gypv8sh.py ../out/Debug/d8 ../chrome/third_party/mock4js/mock4js.js ../third_party/accessibility-audit/axs_testing.js ../chrome/test/data/webui/test_api.js ../chrome/test/base/js2gtest.js unit "webapp/all_js_load.gtestjs" "chrome/webapp/all_js_load.gtestjs" "../out/Debug/obj/remoting/remoting_unittests.gen/chrome/webapp/all_js_load-gen.cc" "../out/Debug/test_data/chrome/webapp/all_js_load.gtestjs"
../out/Debug/d8: error while loading shared libraries: libicui18n.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "../tools/gypv8sh.py", line 55, in <module>
    sys.exit(main())
  File "../tools/gypv8sh.py", line 44, in main
    subprocess.check_call(cmd, stdin=subprocess.PIPE, stdout=f)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../out/Debug/d8', '-e', 'arguments=["../chrome/test/base/js2gtest.js", "webapp/all_js_load.gtestjs", "chrome/webapp/all_js_load.gtestjs", "../out/Debug/obj/remoting/remoting_unittests.gen/chrome/webapp/all_js_load-gen.cc", "unit"]', '../chrome/third_party/mock4js/mock4js.js', '../third_party/accessibility-audit/axs_testing.js', '../chrome/test/data/webui/test_api.js', '../chrome/test/base/js2gtest.js']' returned non-zero exit status 127
FAILED: cd ../../remoting; python ../tools/gypv8sh.py ../out/Debug/d8 ../chrome/third_party/mock4js/mock4js.js ../third_party/accessibility-audit/axs_testing.js ../chrome/test/data/webui/test_api.js ../chrome/test/base/js2gtest.js unit "webapp/browser_globals.gtestjs" "chrome/webapp/browser_globals.gtestjs" "../out/Debug/obj/remoting/remoting_unittests.gen/chrome/webapp/browser_globals-gen.cc" "../out/Debug/test_data/chrome/webapp/browser_globals.gtestjs"
../out/Debug/d8: error while loading shared libraries: libicui18n.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "../tools/gypv8sh.py", line 55, in <module>
    sys.exit(main())
  File "../tools/gypv8sh.py", line 44, in main
    subprocess.check_call(cmd, stdin=subprocess.PIPE, stdout=f)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../out/Debug/d8', '-e', 'arguments=["../chrome/test/base/js2gtest.js", "webapp/browser_globals.gtestjs", "chrome/webapp/browser_globals.gtestjs", "../out/Debug/obj/remoting/remoting_unittests.gen/chrome/webapp/browser_globals-gen.cc", "unit"]', '../chrome/third_party/mock4js/mock4js.js', '../third_party/accessibility-audit/axs_testing.js', '../chrome/test/data/webui/test_api.js', '../chrome/test/base/js2gtest.js']' returned non-zero exit status 127
FAILED: cd ../../remoting; python ../tools/gypv8sh.py ../out/Debug/d8 ../chrome/third_party/mock4js/mock4js.js ../third_party/accessibility-audit/axs_testing.js ../chrome/test/data/webui/test_api.js ../chrome/test/base/js2gtest.js unit "webapp/format_iq.gtestjs" "chrome/webapp/format_iq.gtestjs" "../out/Debug/obj/remoting/remoting_unittests.gen/chrome/webapp/format_iq-gen.cc" "../out/Debug/test_data/chrome/webapp/format_iq.gtestjs"
../out/Debug/d8: error while loading shared libraries: libicui18n.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "../tools/gypv8sh.py", line 55, in <module>
    sys.exit(main())
  File "../tools/gypv8sh.py", line 44, in main
    subprocess.check_call(cmd, stdin=subprocess.PIPE, stdout=f)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../out/Debug/d8', '-e', 'arguments=["../chrome/test/base/js2gtest.js", "webapp/format_iq.gtestjs", "chrome/webapp/format_iq.gtestjs", "../out/Debug/obj/remoting/remoting_unittests.gen/chrome/webapp/format_iq-gen.cc", "unit"]', '../chrome/third_party/mock4js/mock4js.js', '../third_party/accessibility-audit/axs_testing.js', '../chrome/test/data/webui/test_api.js', '../chrome/test/base/js2gtest.js']' returned non-zero exit status 127
ninja: build stopped: subcommand failed.

> When "linux_use_gold_binary" is set, we now use gold from third_party/binutils rather than third_party/gold (allowing us to remove third_party/gold dependency).
> 
> As third_party/binutils is 2.24, this also satisfies the binutils version requirements for Debug Fission. Thus, when building with clang on Ubuntu Precise it should now be enabled. This should cause a significant speedup in linking for most chrome developers on Linux.
> 
> Requires;
>  * https://codereview.chromium.org/209853003/ - Adding binutils as a DEPS to allow DebugFission on Ubuntu Precise when compiling with clang.
> 
> BUG=352046
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=261778
> 
> Review URL: https://codereview.chromium.org/196573022

TBR=mithro@mithis.com

Review URL: https://codereview.chromium.org/225093013

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 6ea2c6c2c8e7244c391bc651a76551b5034bf2ff