Fix break building v8 with goma
The error is caused by missing '-m32' parameter when building v8 for host.
  CXX(host) out/Release/obj.host/v8_base/v8/src/accessors.o
v8/src/globals.h:120:2: error: #error Target architecture arm is only supported on arm and ia32 host

v8/build/common.gypi tests if the compiler supports -m32:
  'm32flag': '<!((echo | $(echo ${CXX_host:-$(which g++)}) -m32 -E - > /dev/null 2>&1) && echo -n "-m32" || true)',
but goma is confused by the environment variable GOMA_WRAPPER and exits
with an error:
  GOMA_WRAPPER=<anything>: unkown GOMA_ parameter
and the gyp script thinks that the compiler doesn't support -m32.

Rename GOMA_WRAPPER to ANDROID_GOMA_WRAPPER to avoid confusing goma.

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 4aef1770f2cb1e2bb208c96538538ec98abe0540