Revert 268019 "Add hpack_fuzz_wrapper to chromium_builder_asan."
Broke windows compile:

  FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\net\spdy\fuzzing\hpack_fuzz_wrapper.hpack_fuzz_wrapper.obj.rsp /c ..\..\net\spdy\fuzzing\hpack_fuzz_wrapper.cc /Foobj\net\spdy\fuzzing\hpack_fuzz_wrapper.hpack_fuzz_wrapper.obj /Fdobj\net\hpack_fuzz_wrapper.cc.pdb 
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_fuzz_wrapper.cc(38) :error C2440: '<function-style-cast>' : cannot convert from 'std::string' to 'base::FilePath'
          No constructor could take the source type, or constructor overload resolution was ambiguous
  FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\net\spdy\fuzzing\hpack_example_generator.hpack_example_generator.obj.rsp /c ..\..\net\spdy\fuzzing\hpack_example_generator.cc /Foobj\net\spdy\fuzzing\hpack_example_generator.hpack_example_generator.obj /Fdobj\net\hpack_example_generator.cc.pdb 
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_example_generator.cc(51) :error C2440: '<function-style-cast>' : cannot convert from 'std::string' to 'base::FilePath'
          No constructor could take the source type, or constructor overload resolution was ambiguous
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_example_generator.cc(52) :error C2664: 'base::File::File(base::File::RValue)' : cannot convert argument 1 from 'int' to 'base::File &'
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_example_generator.cc(68) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_example_generator.cc(69) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
  FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\net\spdy\fuzzing\hpack_fuzz_mutator.hpack_fuzz_mutator.obj.rsp /c ..\..\net\spdy\fuzzing\hpack_fuzz_mutator.cc /Foobj\net\spdy\fuzzing\hpack_fuzz_mutator.hpack_fuzz_mutator.obj /Fdobj\net\hpack_fuzz_mutator.cc.pdb 
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_fuzz_mutator.cc(53) :error C2440: '<function-style-cast>' : cannot convert from 'std::string' to 'base::FilePath'
          No constructor could take the source type, or constructor overload resolution was ambiguous
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_fuzz_mutator.cc(56) :error C2440: '<function-style-cast>' : cannot convert from 'std::string' to 'base::FilePath'
          No constructor could take the source type, or constructor overload resolution was ambiguous
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_fuzz_mutator.cc(57) :error C2664: 'base::File::File(base::File::RValue)' : cannot convert argument 1 from 'int' to 'base::File &'
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_fuzz_mutator.cc(72) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
  c:\b\build\slave\cr-win-rel-x64\build\src\net\spdy\fuzzing\hpack_fuzz_mutator.cc(73) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

> Add hpack_fuzz_wrapper to chromium_builder_asan.
> 
> BUG=353237
> 
> Review URL: https://codereview.chromium.org/266003005

TBR=jgraettinger@chromium.org

Review URL: https://codereview.chromium.org/268863002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 0bf0190a99a0ec4ec7906f379bf26f8981d7d05d